name: .NET

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore MagicEvents.Api.Service/src/MagicEvents.Api.Service.Api/MagicEvents.Api.Service.Api.csproj
    - name: Build
      run: dotnet build --no-restore MagicEvents.Api.Service/src/MagicEvents.Api.Service.Api/MagicEvents.Api.Service.Api.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal MagicEvents.Api.Service/tests/MagicEvents.Api.Service.IntegrationTests/MagicEvents.Api.Service.IntegrationTests.csproj
